#pragma once

const int SCREEN_INDEX_GAMEPLAY_SCREEN = 0;
const int SCREEN_INDEX_CREDITS_SCREEN = 1;
const int SCREEN_INDEX_LAUNCH_SCREEN = 2;
const int SCREEN_INDEX_MAINMENU_SCREEN = 3;
const int SCREEN_INDEX_INF_SCREEN = 4;